//Steven Volocyk, Lecture 001
/* This program reads a text file of semi-colon deliminated
integers generated by strgen, and displays the numbers
in the file, one number per line, without the semicolons*/
#include <stdio.h>
#include <assert.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdlib.h>

int
main(int argc, char *argv[]) {

	if (argc != 2) {
		fprintf(stderr, "usage: strcat <file> \n");
		exit(1);
	}

	char *infile = argv[1];
	FILE *fp = fopen(infile, "r");
	assert(fp != NULL);

	int number;
	while (fscanf(fp, "%d;", &number) == 1) {
		printf("%d\n", number);
	}
	fclose(fp);

	return 0;
}