//Steven Volocyk, Lecture 001
/* This tool takes a file in str format (as generated by strgen ) 
and writes out both an integer (binary) version of the same, 
as well as a modified version of the str format including a space 
between the negative symbol and the number itself */
#include <stdio.h>
#include <assert.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdlib.h>

int main (int argc, char *argv[]) {

    if (argc != 4) {
        fprintf(stderr, "usage: strtoboth <inputfile1> <outputfile1> <outputfile2>");
        exit(1);
    }

    char *infile = argv[1]; // for file input
    char *outfile = argv[2]; // for file output
    FILE *fp = fopen(infile, "r");/// file pointer
    FILE *fpout = fopen(outfile, "w");//file pointer
    assert (fp != NULL);
    assert (fpout != NULL);

    int number;
    while (fscanf(fp, "%d;", &number) == 1) {
        if (number < 0) {
            number = abs(number);
            fprintf(fpout, "- %d\n", number);
        }else { 
        fprintf(fpout, "%d\n", number);
        }
    }
    fclose(fp);
    fclose(fpout);

    int readFile; //input
    int outputFile;//output
    int ret = 0; //return statement for error checking
    int i = 0;//loop control
    if ((readFile = open(argv[1], O_RDONLY)) < 0) {
        /*file didn't open */
        printf("Could not open file %s\n", argv[1]);
        exit(1);
    }

    if ((outputFile = open(argv[3], O_WRONLY | O_CREAT | O_TRUNC, S_IRWXU)) >= 0) {
        while ((read(readFile, &i, sizeof(int)) > 0)) {
           if(write(outputFile, &i, sizeof(int)) != sizeof(int)) {
            printf ("bad write to file %s\n", argv[2]);
            exit(1);
           }
        }    
    }
    else {
        printf("could not open file %s\n", argv[3]);
        ret = 1;
    }
    close(readFile);
    close(outputFile);
    return ret;
}